apiVersion: v2
name: longhorn-homelab
description: Longhorn via official chart (dependency)
type: application
version: 0.1.0
dependencies:
  - name: longhorn
    repository: https://charts.longhorn.io
    version: "1.8.1"
