longhorn:
  preUpgradeChecker:
    jobEnabled: false

  csi:
    snapshotterReplicaCount: 0
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1

  defaultSettings:
    backupstorePollInterval: "0"
