apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-argo-dags-longhorn
  namespace: airflow-argo
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
