apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-kubernetes
  namespace: vault-secrets-operator
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-secrets-reader
    serviceAccount: default
  allowedNamespaces:
    - mlflow
    - evidently
    - airflow
    - jupyterhub
    - odoo
    - monitoring
    - glance
    - argocd
    - solidtime
    - unity-catalog
