apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: solidtime-postgres
  namespace: solidtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-secrets-operator/vault-auth-kubernetes
  mount: secret
  type: kv-v2
  path: solidtime/postgres
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: solidtime-app
    - kind: Deployment
      name: solidtime-worker
  destination:
    create: true
    overwrite: true
    name: solidtime-postgres-credentials
