apiVersion: v2
name: monitoring-homelab
description: Kube Prometheus Stack via prometheus-community (dependency)
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    repository: oci://ghcr.io/prometheus-community/charts
    version: "67.2.0"
