pihole:
  hostNetwork: "true"
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
  persistentVolumeClaim:
    enabled: false
    size: "500Mi"
    storageClassName: longhorn
  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 127.0.0.1
  serviceDhcp:
    enabled: false
  serviceDns:
    type: ClusterIP
  serviceWeb:
    type: ClusterIP
  ingress:
    enabled: false
  admin:
    enabled: true
    existingSecret: pihole-admin-from-vault
    passwordKey: password
