apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: evidently-postgres
  namespace: evidently
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-secrets-operator/vault-auth-kubernetes
  mount: secret
  type: kv-v2
  path: evidently/postgres
  refreshAfter: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: evidently-ui
  destination:
    create: true
    overwrite: true
    name: evidently-postgres-credentials
