apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: odoo-database
  namespace: odoo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: odoo
  owner: odoo
  cluster:
    name: odoo-postgres
  databaseReclaimPolicy: delete

