apiVersion: v1
kind: Secret
metadata:
  name: helm-jellyfin
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: jellyfin-helm
  url: https://jellyfin.github.io/jellyfin-helm
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-gabe565
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: gabe565
  url: https://charts.gabe565.com
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-community-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: community-charts
  url: https://community-charts.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-jupyterhub
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: jupyterhub
  url: https://jupyterhub.github.io/helm-chart
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-prometheus-community
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-longhorn
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: longhorn
  url: https://charts.longhorn.io
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-spark-operator
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: spark-operator
  url: https://kubeflow.github.io/spark-operator
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-apache-airflow
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: apache-airflow
  url: https://airflow.apache.org
