apiVersion: v2
name: airflow-homelab
description: Airflow via official Apache chart (dependency)
type: application
version: 0.1.0
dependencies:
  - name: airflow
    repository: https://airflow.apache.org
    version: "1.14.0"
