apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-longhorn
  namespace: airflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
