airflow:
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      argocd.argoproj.io/hook: Sync
  executor: KubernetesExecutor
  postgresql:
    enabled: false
  fernetKeySecretName: airflow-app-secrets
  jwtSecretName: airflow-app-secrets
  apiSecretKeySecretName: airflow-app-secrets
  enableBuiltInSecretEnvVars:
    AIRFLOW__CORE__FERNET_KEY: false
    AIRFLOW__API_AUTH__JWT_SECRET: false
    AIRFLOW__API__SECRET_KEY: false
    AIRFLOW__WEBSERVER__SECRET_KEY: false
  images:
    migrationsWaitTimeout: 120
    airflow:
      repository: apache/airflow
      tag: "3.0.2"
      pullPolicy: IfNotPresent
  defaultAirflowTag: "3.0.2"
  defaultAirflowRepository: apache/airflow
  dags:
    persistence:
      enabled: true
      existingClaim: airflow-dags-rwx
  service:
    type: ClusterIP
    ports:
      airflowui: 8080
  ingress:
    web:
      enabled: false
  env:
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "False"
    - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
      value: "True"
  secret:
    - envName: AIRFLOW__CORE__FERNET_KEY
      secretName: airflow-app-secrets
      secretKey: fernetKey
    - envName: AIRFLOW__API_AUTH__JWT_SECRET
      secretName: airflow-app-secrets
      secretKey: jwtSecret
    - envName: AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD
      secretName: airflow-app-secrets
      secretKey: defaultUserPassword
  webserverSecretKeySecretName: airflow-app-secrets
  data:
    metadataSecretName: airflow-postgres-app
    resultBackendSecretName: airflow-postgres-app
  webserver:
    defaultUser:
      enabled: true
      role: Admin
      username: admin
      email: admin@rendonindustries.com
      firstName: Admin
      lastName: User
  logs:
    persistence:
      enabled: false
  workers:
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
  scheduler:
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
  triggerer:
    enabled: true
    replicas: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 1000m
    livenessProbe:
      timeoutSeconds: 30
      periodSeconds: 60
      failureThreshold: 5
