apiVersion: v2
name: jellyfin-homelab
description: Jellyfin via official chart (dependency)
type: application
version: 0.1.0
dependencies:
  - name: jellyfin
    repository: https://jellyfin.github.io/jellyfin-helm
    version: "2.6.0"
