apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: airflow/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: airflow
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status
        - /spec
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/selector
        - /spec/template
    - kind: Secret
      name: airflow-fernet-key
      jqPathExpressions:
        - .data
    - kind: Secret
      name: airflow-jwt-secret
      jqPathExpressions:
        - .data
    - kind: Secret
      name: airflow-api-secret-key
      jqPathExpressions:
        - .data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
