apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: airflow/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: airflow
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status
        - /spec
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].env
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.template.spec.containers[].env
    - group: batch
      kind: Job
      jqPathExpressions:
        - .spec.template.spec.containers[].env
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
