apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: qbittorrent/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: qbittorrent
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
