apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solidtime
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: solidtime/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: solidtime
  destination:
    server: https://kubernetes.default.svc
    namespace: solidtime
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status
        - /spec
    - group: postgresql.cnpg.io
      kind: Cluster
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: postgresql.cnpg.io
      kind: Database
      jsonPointers:
        - /status
    - group: postgresql.cnpg.io
      kind: Database
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
