apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: spark-operator/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: spark-operator
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /status
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status
    - group: batch
      kind: Job
      jsonPointers:
        - /status
    - group: ""
      kind: Service
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
        - .spec.clusterIP
    - group: ""
      kind: Secret
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[].clientConfig.caBundle
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
        - .status
    - group: ""
      kind: ConfigMap
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: ""
      kind: ServiceAccount
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
        - .secrets
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: sparkapplications.sparkoperator.k8s.io
      jqPathExpressions:
        - .spec.versions
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: scheduledsparkapplications.sparkoperator.k8s.io
      jqPathExpressions:
        - .spec.versions
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
