apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: spark-operator/infra
    - repoURL: git@github.com:LuisAlfonsoGarciaCamacho/homelab.git
      targetRevision: main
      path: spark-operator
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
    - group: ""
      kind: Service
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
        - .spec.clusterIP
    - group: ""
      kind: Secret
      jqPathExpressions:
        - .metadata.resourceVersion
        - .metadata.managedFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
