apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-operator
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/component: controller
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-operator
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
