apiVersion: v2
name: mlflow-homelab
description: MLflow via community-charts (dependency)
type: application
version: 0.1.0
dependencies:
  - name: mlflow
    repository: https://community-charts.github.io/helm-charts
    version: "1.8.1"
