jupyterhub:
  hub:
    readinessProbe:
      initialDelaySeconds: 120
      periodSeconds: 5
      failureThreshold: 60
    livenessProbe:
      initialDelaySeconds: 180
    config:
      JupyterHub:
        authenticator_class: dummy
    db:
      type: postgres
    extraEnv:
      - name: JUPYTERHUB_DB_URL
        valueFrom:
          secretKeyRef:
            name: jupyterhub-postgres-app
            key: url
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 512Mi
        cpu: 500m

  proxy:
    service:
      type: ClusterIP

  singleuser:
    image:
      name: jupyter/pyspark-notebook
      tag: latest
    startTimeout: 600
    cloudMetadata:
      blockWithIptables: false
    storage:
      type: dynamic
      extraLabels: {}
      dynamic:
        storageClass: longhorn
      capacity: 10Gi
    memory:
      guarantee: 1G
      limit: 2G
    cpu:
      guarantee: 0.5
      limit: 2
    cmd: null

  ingress:
    enabled: true
    annotations:
      cloudflare-tunnel-ingress-controller.strrl.dev/backend-protocol: http
      kubernetes.io/ingress.class: cloudflare-tunnel
    hosts:
      - jupyter.rendonindustries.com

  scheduling:
    userScheduler:
      replicas: 1

  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
