apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: unity-catalog-postgres
  namespace: unity-catalog
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: ucdb
      owner: unitycatalog
      secret:
        name: unity-catalog-postgres-app
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1000m"
