apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: unity-catalog-postgres
  namespace: unity-catalog
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-secrets-operator/vault-auth-kubernetes
  mount: secret
  type: kv-v2
  path: unity-catalog/postgres
  refreshAfter: 60s
  destination:
    create: true
    overwrite: true
    name: unity-catalog-postgres-app
