apiVersion: v1
kind: ConfigMap
metadata:
  name: solidtime-config
  namespace: solidtime
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://solidtime.rendonindustries.com
  APP_FORCE_HTTPS: "true"
  APP_ENABLE_REGISTRATION: "false"
  TRUSTED_PROXIES: "0.0.0.0/0,2000:0:0:0:0:0:0:0/3"
  DB_HOST: solidtime-postgres-rw.solidtime.svc.cluster.local
  DB_PORT: "5432"
  DB_DATABASE: solidtime
  DB_SSLMODE: prefer
  QUEUE_CONNECTION: database
  LOG_CHANNEL: stderr
  LOG_LEVEL: debug
  FILESYSTEM_DISK: local
  PUBLIC_FILESYSTEM_DISK: public
  AUTO_DB_MIGRATE: "true"
