apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: airflow-database
  namespace: airflow
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  name: airflow
  owner: airflow
  cluster:
    name: airflow-postgres
  databaseReclaimPolicy: delete
